version: "3"

services:
  database:
    image: postgres
    container_name: database_medium
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=medium
    volumes:
      #- C:\\caminho\\pasta:/var/lib/postgresql/data